language: python

python:
  - "3.8"

cache: pip

services:
  - docker

before_install:
- docker pull rbarile17/py_cb_recsys
- docker run -d -p 127.0.0.1:80:4567 rbarile17/py_cb_recsys /bin/sh -c "cd /root/py_cb_recsys; bundle exec foreman start;"

script:
  - py.test --cov-report term-missing --cov app -v

git:
  depth: false