language: python

python:
  - "3.8"

cache: pip

services:
  - docker

before_install:
  - docker build -t autore/py_cb_recsys .
  - docker run -d -p 127.0.0.1:80:4567 autore/py_cb_recsys /bin/sh -c "cd /root/py_cb_recsys; bundle exec foreman start;"
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - python --version
  - pip install -U pip
install:
- pip install numpy
- pip install wheel
- pip install gensim
- pip install nltk
- pip install babelpy
- pip install mysql
- pip install mysql-connector-python

script:
  - python -m unittest
after_success:
  - python -c 'import lucene; print(lucene.VERSION)'
git:
  depth: false
