env:
  global:
    - CI_NAME:travis-pro
    - COVERALLS_REPO_TOKEN=m7F9CNmqoMWrzUv0lcmojwOCqk7PGjDG8

sudo: required

language: python

python:
  - "3.8"

cache: pip

services:
  - docker

script:
  - docker pull rbarile17/framework_dependencies
  - container_id=$(docker run -d -it rbarile17/framework_dependencies)
  - docker exec -it $container_id coverage run --source=src -m unittest
  - docker exec -it $container_id TRAVIS_JOB_ID=$TRAVIS_JOB_ID TRAVIS_BRANCH=$TRAVIS_BRANCH COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN coveralls
  - docker stop $container_id
  - docker container rm $container_id
  
git:
  depth: false
