language: python

python:
  - "3.8"

cache: pip

services:
  - docker

script:
  - docker build -t testing/py_cb_recsys .
  - container_id=$(docker run -d -i testing/py_cb_recsys)
  - docker exec -it $container_id coverage run -m unittest
  - docker exec -it $container_id coverage report -m
  
git:
  depth: false
