language: python

python:
  - "3.8"

cache: pip

services:
  - docker

script:
  - docker pull rbarile17/framework_dependencies
  - container_id=$(docker run -d -it rbarile17/framework_dependencies)
  - docker exec -it $container_id coverage run --source=src -m unittest
  - docker exec -it $container_id coveralls
  - docker stop $container_id
  - docker container rm $container_id
  
git:
  depth: false
