language: python

python:
  - "3.8"

cache: pip

services:
  - docker

before_install:
  - docker pull rbarile17/py_cb_recsys
  - docker run -d -p 127.0.0.1:80:4567 rbarile17/py_cb_recsys /bin/sh -c "cd /root/py_cb_recsys; bundle exec foreman start;"
  - python --version
  - pip install -U pip
#  - pip install -U pytest
#  - pip install codecov
install:
- pip install -r requirements.txt . # install package + test dependencies
#- pip install numpy
#- pip install wheel
#- pip install gensim
#- pip install nltk
#- pip install babelpy
#- pip install mysql
#- pip install mysql-connector-python

script:
  - cd test
  - python -m unittest
after_success:
 - codecov # submit coverage
# - python run.py # non si può runnare dopo lo script
git:
  depth: false
